---
# Install and configure Elasticsearch, Kibana, and Logstash

- name: Install prerequisites
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Elasticsearch GPG key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add Elastic 7.x repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present

- name: Install Elasticsearch, Kibana, and Logstash
  apt:
    name:
      - elasticsearch=7.17.9
      - kibana=7.17.9
      - logstash=1:7.17.9-1
    state: present
    update_cache: yes

- name: Configure Elasticsearch to listen on all interfaces
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^#?network.host:'
    line: 'network.host: 0.0.0.0'

- name: Set discovery type to single-node
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'discovery.type: single-node'

- name: Set JVM heap size (2 GB)
  copy:
    dest: /etc/elasticsearch/jvm.options.d/heap.options
    content: |
      -Xms2g
      -Xmx2g
    owner: root
    group: root
    mode: '0644'

- name: Increase vm.max_map_count
  sysctl:
    name: vm.max_map_count
    value: '262144'
    state: present
    sysctl_set: yes

- name: Enable and start Elasticsearch
  systemd:
    name: elasticsearch
    enabled: true
    state: started

- name: Enable and start Kibana
  systemd:
    name: kibana
    enabled: true
    state: started

- name: Enable and start Logstash
  systemd:
    name: logstash
    enabled: true
    state: started
